services:
  stub-civil-claims-api:
    build:
      context: ./stub-civil-claims-api
      dockerfile: Dockerfile
    container_name: stub-civil-claims-api
    ports:
      - "8090:8090"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8080
  stub-oidc-server:
    build:
      context: ./stub-oidc-server
      dockerfile: Dockerfile
    container_name: stub-oidc-server
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8081
    volumes:
      - ./config/external.yml:/opt/stub-oidc-server/config/external.yml:ro

