services:
  stub-civil-claims-api:
    build:
      context: ./stub-civil-claims-api
      dockerfile: Dockerfile
    container_name: stub-civil-claims-api
    ports:
      - "8090:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8080

