server:
  port: 8091
  servlet:
    context-path: /mock-issuer
auth:
  mock:
    issuer: http://localhost:8091/mock-issuer
    redirect-ssr: http://localhost:8080/login/oauth2/code/ssr

spring:
  thymeleaf:
    cache: false
