DROP TABLE IF EXISTS claims;
DROP TABLE IF EXISTS submissions;

CREATE TABLE IF NOT EXISTS claims (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ufn                 VARCHAR(20)    NOT NULL,
    client              VARCHAR(50)    NOT NULL,
    category            VARCHAR(50)    NOT NULL,
    concluded           DATE           NOT NULL,
    fee_type            VARCHAR(50)    NOT NULL,
    claimed             DECIMAL(10, 2) NOT NULL,
    submission_id       UUID,
    provider_user_id    UUID
);