name: Build and deploy after PR merged

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: 'corretto'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build and test
        run: ./gradlew build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Integration test
        run: ./gradlew integrationTest --tests '*IntegrationTest'

      - name: Test coverage verification
        run: ./gradlew jacocoTestCoverageVerification

      - name: Upload test results (all modules)
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: test-results
          path: |
            **/build/test-results/**
          retention-days: 14

      - name: Upload checkstyle report
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: checkstyle-report
          path: |
            **/build/reports/checkstyle/**
          retention-days: 14

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: test-report
          path: |
            **/build/reports/tests/**
          retention-days: 14

      - name: Upload jacoco coverage report
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: jacoco-coverage-report
          path: |
            **/build/reports/jacoco/**
          retention-days: 14

  vulnerability-report:
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: 'corretto'

      - name: Setup Snyk
        uses: snyk/actions/setup@master

      - name: Run Snyk to check app for vulnerabilities
        run: snyk monitor --severity-threshold=high
        continue-on-error: true

      - name: Generate sarif Snyk report
        run: snyk test --sarif-file-output=snyk-app.sarif
        continue-on-error: true

      # Fix/hack for Snyk's sarif file to avoid this error uploading to GitHub.
      # See https://github.com/github/codeql-action/issues/2187 for more context.
      - name: Fix undefined values
        run: |
          sed -i 's/"security-severity": "undefined"/"security-severity": "0"/g' snyk-app.sarif

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: snyk-app.sarif


  ecr:
    needs: build-test
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: stub-civil-claims-api
            context: ./stub-civil-claims-api
            dockerfile: ./stub-civil-claims-api/Dockerfile
            ecr-repository: ${{ vars.STUB_CIVIL_CLAIMS_API_ECR_REPOSITORY}}
            aws-region: ${{ vars.STUB_CIVIL_CLAIMS_API_ECR_REGION}}
          - name: stub-oidc-server
            context: ./stub-oidc-server
            dockerfile: ./stub-oidc-server/Dockerfile
            ecr-repository: ${{ vars.STUB_OIDC_SERVER_ECR_REPOSITORY }}
            aws-region: ${{ vars.STUB_OIDC_SERVER_ECR_REGION }}
    env:
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: 'corretto'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build and test
        run: ./gradlew :${{ matrix.name }}:build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS creds (stub-civil-claims-api)
        if: matrix.name == 'stub-civil-claims-api'
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.STUB_CIVIL_CLAIMS_API_ECR_ROLE_TO_ASSUME }}
          aws-region: ${{ matrix.aws-region }}

      - name: Configure AWS creds (stub-oidc-server)
        if: matrix.name == 'stub-oidc-server'
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.STUB_OIDC_SERVER_ECR_ROLE_TO_ASSUME }}
          aws-region: ${{ matrix.aws-region }}

      - name: login to registry
        uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Cache Docker layers
        uses: actions/cache@v5
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}-${{ matrix.name }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push image with local action
        uses: ./.github/actions/build_and_push
        with:
          image_registry: ${{ secrets.ECR_REGISTRY_URL }}
          image_repo: ${{ matrix.ecr-repository }}
          dockerfile_path: ${{ matrix.dockerfile }}
          build_context: ${{ matrix.context }} 
          image_tag: ${{ env.IMAGE_TAG }}

  stub-civil-claims-deploy-dev:
        environment: dev
        runs-on: ubuntu-latest
        needs:
          - ecr
          - vulnerability-report
        steps:
          - name: Checkout
            uses: actions/checkout@v6

          - name: Deploy to Development
            uses: ./.github/actions/deploy
            with:
              ecr-repository:  ${{ vars.STUB_CIVIL_CLAIMS_API_ECR_REPOSITORY}}
              ecr-registry_url: ${{ secrets.ECR_REGISTRY_URL }}
              kube-cert: ${{ secrets.KUBE_CERT }}
              kube-token: ${{ secrets.KUBE_TOKEN }}
              kube-cluster: ${{ secrets.KUBE_CLUSTER }}
              kube-namespace: ${{ secrets.KUBE_NAMESPACE }}
              app-environment: dev
              session_secret: ${{ secrets.SESSION_SECRET }}
              service_name: ${{ vars.SERVICE_NAME }}
              service_phase: ${{ vars.SERVICE_PHASE }}
              department_name: ${{ vars.DEPARTMENT_NAME }}
              department_url: ${{ vars.DEPARTMENT_URL }}
              contact_email: ${{ vars.CONTACT_EMAIL }}
              service_url: ${{ vars.SERVICE_URL }}
              session_name: ${{ vars.SESSION_NAME}}
              ratelimit_headers_enabled: ${{ vars.RATELIMIT_HEADERS_ENABLED }}
              ratelimit_storage_uri: ${{ vars.RATELIMIT_STORAGE_URI }}
              ratelimit_max: ${{ vars.RATE_LIMIT_MAX }}
              ratewindow_ms: ${{ vars.RATE_WINDOW_MS }}  
              service_artifact: 'stub-civil-claims-api'           

  
  run-e2e:
    needs: ecr
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: generate_token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ministryofjustice

      - name: Trigger and Wait for E2E Tests
        uses: the-actions-org/workflow-dispatch@v4
        with:
          workflow: qa-ci.yml
          # Combine owner and repo name here:
          repo: ministryofjustice/claim-assess-regression-tests
          token: ${{ steps.generate_token.outputs.token }}
          ref: main
          # inputs: '{"environment": "uat"}'
          wait-for-completion: true
          display-workflow-run-url: true   

  stub-civil-claims-deploy-uat:
        environment: uat
        runs-on: ubuntu-latest
        needs:
          - run-e2e
          - vulnerability-report
        steps:
          - name: Checkout
            uses: actions/checkout@v6

          - name: Deploy to UAT
            uses: ./.github/actions/deploy
            with:
              ecr-repository:  ${{ vars.STUB_CIVIL_CLAIMS_API_ECR_REPOSITORY}}
              ecr-registry_url: ${{ secrets.ECR_REGISTRY_URL }}
              kube-cert: ${{ secrets.KUBE_CERT }}
              kube-token: ${{ secrets.KUBE_TOKEN }}
              kube-cluster: ${{ secrets.KUBE_CLUSTER }}
              kube-namespace: ${{ secrets.KUBE_NAMESPACE }}
              app-environment: uat
              session_secret: ${{ secrets.SESSION_SECRET }}
              service_name: ${{ vars.SERVICE_NAME }}
              service_phase: ${{ vars.SERVICE_PHASE }}
              department_name: ${{ vars.DEPARTMENT_NAME }}
              department_url: ${{ vars.DEPARTMENT_URL }}
              contact_email: ${{ vars.CONTACT_EMAIL }}
              service_url: ${{ vars.SERVICE_URL }}
              session_name: ${{ vars.SESSION_NAME}}
              ratelimit_headers_enabled: ${{ vars.RATELIMIT_HEADERS_ENABLED }}
              ratelimit_storage_uri: ${{ vars.RATELIMIT_STORAGE_URI }}
              ratelimit_max: ${{ vars.RATE_LIMIT_MAX }}
              ratewindow_ms: ${{ vars.RATE_WINDOW_MS }}  
              service_artifact: 'stub-civil-claims-api'   

     

  deploy-staging:
        environment: staging
        runs-on: ubuntu-latest
        needs:
          - run-e2e
          - vulnerability-report
        steps:
          - name: Checkout
            uses: actions/checkout@v6

          - name: Deploy to Staging
            uses: ./.github/actions/deploy
            with:
              ecr-repository: ${{ vars.STUB_CIVIL_CLAIMS_API_ECR_REPOSITORY }}
              ecr-registry_url: ${{ secrets.ECR_REGISTRY_URL }}
              kube-cert: ${{ secrets.KUBE_CERT }}
              kube-token: ${{ secrets.KUBE_TOKEN }}
              kube-cluster: ${{ secrets.KUBE_CLUSTER }}
              kube-namespace: ${{ secrets.KUBE_NAMESPACE }}
              app-environment: staging
              session_secret: ${{ secrets.SESSION_SECRET }}
              service_name: ${{ vars.SERVICE_NAME }}
              service_phase: ${{ vars.SERVICE_PHASE }}
              department_name: ${{ vars.DEPARTMENT_NAME }}
              department_url: ${{ vars.DEPARTMENT_URL }}
              contact_email: ${{ vars.CONTACT_EMAIL }}
              service_url: ${{ vars.SERVICE_URL }}
              session_name: ${{ vars.SESSION_NAME}}
              ratelimit_headers_enabled: ${{ vars.RATELIMIT_HEADERS_ENABLED }}
              ratelimit_storage_uri: ${{ vars.RATELIMIT_STORAGE_URI }}
              ratelimit_max: ${{ vars.RATE_LIMIT_MAX }}
              ratewindow_ms: ${{ vars.RATE_WINDOW_MS }}
              service_artifact: 'stub-civil-claims-api'               

